import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { http, HttpResponse } from 'msw';
import { errorBody, server } from '@tests/utils/server';
import { renderWithProviders } from '@tests/utils/renderWithProviders';
import { TtsComposer } from './TtsComposer';

describe('TtsComposer', () => {
  it('disables Generate for blank text and enables it after typing', async () => {
    const user = userEvent.setup();
    renderWithProviders(<TtsComposer />, {
      preloadedState: { composer: { text: '', lastAudio: null } },
    });
    const button = screen.getByRole('button', { name: /generate audio/i });
    expect(button).toBeDisabled();
    await user.type(screen.getByRole('textbox', { name: /persian text/i }), 'سلام');
    expect(button).toBeEnabled();
  });

  it('shows the empty state, then the preview with cache metadata after generating', async () => {
    const user = userEvent.setup();
    const { store } = renderWithProviders(<TtsComposer />);
    expect(screen.getByText(/no audio generated yet/i)).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: /generate audio/i }));
    await waitFor(() => expect(screen.getByText(/generated by elevenlabs/i)).toBeInTheDocument());
    expect(screen.getByText(/1\.5 s/)).toBeInTheDocument();
    // The page reads the duration to keep Record off for a too long answer (REQ-036).
    expect(store.getState().composer.lastAudio).toMatchObject({
      durationMs: 1500,
      text: store.getState().composer.text,
    });
  });

  it('shows locked text read only and generates the audio of that text (REQ-074)', async () => {
    const user = userEvent.setup();
    let sent: unknown;
    server.use(
      http.post('*/api/tts/generate', async ({ request }) => {
        sent = await request.json();
        return HttpResponse.json({
          id: '11111111-1111-4111-8111-111111111111',
          cache_key: 'a'.repeat(64),
          status: 'AUDIO_GENERATED',
          duration_ms: 1500,
          sample_rate: 24000,
          format: 'pcm_s16le',
          media_url: '/api/assets/audio/11111111-1111-4111-8111-111111111111',
          cache_hit: false,
        });
      }),
    );
    const { store } = renderWithProviders(<TtsComposer lockedText="متن تأییدشده" />, {
      preloadedState: { composer: { text: 'متن دیگری که مدیر نوشته', lastAudio: null } },
    });

    const field = screen.getByRole('textbox', { name: /persian text/i });
    expect(field).toHaveValue('متن تأییدشده');
    expect(field).toHaveAttribute('readonly');
    await user.click(screen.getByRole('button', { name: /generate audio/i }));

    await waitFor(() => expect(sent).toEqual({ text: 'متن تأییدشده' }));
    // What the admin typed before stays in the composer (section 8).
    expect(store.getState().composer.text).toBe('متن دیگری که مدیر نوشته');
  });

  it.each([
    ['elevenlabs_payment', 502, 'ElevenLabs refused the speech because the plan is not paid.'],
    ['elevenlabs_quota', 429, 'ElevenLabs is busy or its quota is used up.'],
    ['elevenlabs_auth', 502, 'The avatar could not speak the answer.'],
  ])('shows the speech message for %s with the code under it', async (code, status, message) => {
    const user = userEvent.setup();
    server.use(
      http.post('*/api/tts/generate', () =>
        HttpResponse.json(errorBody(code, 'Fixed English text.'), { status }),
      ),
    );
    renderWithProviders(<TtsComposer />);

    await user.click(screen.getByRole('button', { name: /generate audio/i }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent(message);
    expect(screen.getByText(code)).toHaveAttribute('dir', 'ltr');
    expect(screen.queryByText(/Fixed English text/)).toBeNull();
  });
});
