import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { renderWithProviders } from '@tests/utils/renderWithProviders';
import { TtsComposer } from './TtsComposer';

describe('TtsComposer', () => {
  it('disables Generate for blank text and enables it after typing', async () => {
    const user = userEvent.setup();
    renderWithProviders(<TtsComposer />, {
      preloadedState: { composer: { text: '', lastAudioAssetId: null } },
    });
    const button = screen.getByRole('button', { name: /generate audio/i });
    expect(button).toBeDisabled();
    await user.type(screen.getByRole('textbox', { name: /persian text/i }), 'سلام');
    expect(button).toBeEnabled();
  });

  it('shows the empty state, then the preview with cache metadata after generating', async () => {
    const user = userEvent.setup();
    renderWithProviders(<TtsComposer />);
    expect(screen.getByText(/no audio generated yet/i)).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: /generate audio/i }));
    await waitFor(() => expect(screen.getByText(/generated by elevenlabs/i)).toBeInTheDocument());
    expect(screen.getByText(/1\.5 s/)).toBeInTheDocument();
  });
});
