import {
  act,
  configure,
  screen,
  waitFor,
  within,
} from '@testing-library/react';
import userEvent, { type UserEvent } from '@testing-library/user-event';
import {
  AxiosError,
  type AxiosAdapter,
  type AxiosResponse,
  type InternalAxiosRequestConfig,
} from 'axios';
import { Route, Routes } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  installMockApi,
  mockRecordingTriggers,
  mockSession,
  resetMockLibrary,
} from '@/data/mock';
import { loadInitialSettings } from '@/features/settings';
import { i18n } from '@/i18n';
import { AdminLibraryPage } from '@/pages/admin/library/AdminLibraryPage';
import { AdminRecordAnswerPage } from '@/pages/admin/library/AdminRecordAnswerPage';
import { apiClient } from '@/shared/api';
import { renderWithProviders } from '../utils/renderWithProviders';

/*
 * The Record answer screen (REQ-034 to REQ-036, REQ-039, REQ-041, REQ-042, REQ-074) against the
 * mock API, which runs the whole recording chain (src/data/mock/handlers.ts). LiveKit is the one
 * part faked here: the browser never joins a room in a test.
 *
 * Mock seed used below: C4Q02 is the `ready` entry (id mock-library-ready, answer
 * 'پاسخ گفتاری نمونه.'), and one finished recording ANS_MOCK_01 is not in the library yet.
 */

vi.mock('@/features/avatar-session/livekitRoom', () => ({
  connectRoom: vi.fn(async () => undefined),
  disconnectRoom: vi.fn(async () => undefined),
  startRoomAudio: vi.fn(async () => undefined),
  setMediaTargets: vi.fn(),
  isRoomConnected: vi.fn(() => true),
}));

const UI_TEST_TIMEOUT = 30_000;
configure({ asyncUtilTimeout: 5_000 });

const READY_TEXT = 'پاسخ گفتاری نمونه.';
const SEED_RECORDING_TEXT = 'متن یک ضبط تمام‌شده که هنوز در کتابخانه نیست.';

let requests: InternalAxiosRequestConfig[] = [];
let override:
  | ((config: InternalAxiosRequestConfig) => AxiosResponse | undefined)
  | undefined;

function reply(
  config: InternalAxiosRequestConfig,
  data: unknown,
  status = 200,
): AxiosResponse {
  return { data, status, statusText: 'OK', headers: {}, config };
}

function errorReply(
  config: InternalAxiosRequestConfig,
  status: number,
  code: string,
) {
  return reply(
    config,
    { error: { code, message: 'Fixed English text.', retryable: false } },
    status,
  );
}

beforeEach(() => {
  vi.useFakeTimers({ shouldAdvanceTime: true });
  installMockApi(apiClient, { delayMs: 0 });
  const mockAdapter = apiClient.defaults.adapter as AxiosAdapter;
  requests = [];
  override = undefined;
  apiClient.defaults.adapter = async (config) => {
    requests.push(config);
    const answer = override?.(config);
    if (answer) {
      if (answer.status >= 400) {
        throw new AxiosError(
          'failed',
          'ERR_BAD_RESPONSE',
          config,
          null,
          answer,
        );
      }
      return answer;
    }
    return mockAdapter(config);
  };
  resetMockLibrary();
  mockSession.set('u-admin');
});

afterEach(async () => {
  vi.useRealTimers();
  await i18n.changeLanguage('en');
});

function setupUser(): UserEvent {
  return userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
}

async function advance(ms: number) {
  await act(async () => {
    await vi.advanceTimersByTimeAsync(ms);
  });
}

function renderAdmin(route: string, language: 'en' | 'fa' = 'en') {
  return renderWithProviders(
    <Routes>
      <Route path="/library" element={<AdminLibraryPage />} />
      <Route path="/library/record" element={<AdminRecordAnswerPage />} />
    </Routes>,
    {
      route,
      locale: language,
      preloadedState: { settings: { ...loadInitialSettings(), language } },
    },
  );
}

function requestsTo(method: string, path: RegExp) {
  return requests.filter(
    (config) =>
      config.method?.toLowerCase() === method && path.test(config.url ?? ''),
  );
}

async function setComposerText(user: UserEvent, text: string) {
  const field = screen.getByRole('textbox', { name: 'Persian text' });
  await user.clear(field);
  await user.click(field);
  await user.paste(text);
}

async function startSession(user: UserEvent) {
  await user.click(screen.getByRole('button', { name: 'Start avatar' }));
  await screen.findByRole('button', { name: 'Close session' });
  await waitFor(() =>
    expect(screen.getByRole('button', { name: 'Start avatar' })).toBeDisabled(),
  );
}

/** Starts and stops a recording, so its finalize job is queued. */
const NEEDS_AUDIO = 'Generate the audio first, so its length can be checked.';

/** Generates the audio of the text on screen, which Record needs (ruling 5). */
async function generateAudio(user: UserEvent) {
  await user.click(screen.getByRole('button', { name: 'Generate audio' }));
  await screen.findByText(/Generated by ElevenLabs/);
}

async function recordAndStop(user: UserEvent) {
  await startSession(user);
  await generateAudio(user);
  await user.click(screen.getByRole('button', { name: 'Start recording' }));
  await user.click(
    await screen.findByRole('button', { name: 'Stop recording' }),
  );
}

/** The mock job answers queued, then running, then done, one step per poll (2 s apart). */
async function waitForJobDone() {
  expect(
    await screen.findByText('Waiting to process the recording'),
  ).toBeInTheDocument();
  await advance(2000);
  expect(
    await screen.findByText('Processing the recording'),
  ).toBeInTheDocument();
  await advance(2000);
  expect(
    await screen.findByText('The recording is ready. Save it to the library.'),
  ).toBeInTheDocument();
}

function saveForm() {
  return screen.getByRole('form', { name: 'Save to library' });
}

async function fillSaveForm(user: UserEvent, form: HTMLElement, key?: string) {
  await user.type(
    within(form).getByRole('textbox', { name: 'Question' }),
    'پرسش تازه',
  );
  await user.type(
    within(form).getByRole('textbox', { name: 'Category number' }),
    '5',
  );
  await user.type(
    within(form).getByRole('textbox', { name: 'Category title' }),
    'دسته پنج',
  );
  if (key)
    await user.type(within(form).getByRole('textbox', { name: /Key/ }), key);
}

/**
 * The screen's own Attach button. Once the recording is done it is also in the unsaved list,
 * which offers its own Attach for the same entry.
 */
function entryAttachButton() {
  const unsaved = screen.queryByRole('region', {
    name: 'Finished recordings not in the library',
  });
  const button = screen
    .getAllByRole('button', { name: 'Attach to this answer' })
    .find((candidate) => !unsaved?.contains(candidate));
  if (!button) throw new Error('the screen has no Attach button of its own');
  return button;
}

/** Records `text` through the mock API, so it is a finished recording no entry uses. */
async function makeFinishedRecording(text: string) {
  const session = await apiClient.post('/api/avatar/session', {});
  const video = await apiClient.post('/api/assets/generate-video', {
    session_id: session.data.id,
    asset_id: 'AVATAR_20260928090000',
    text,
  });
  const { data } = await apiClient.post(
    `/api/assets/video/${video.data.id}/finalize`,
  );
  for (let poll = 0; poll < 3; poll += 1)
    await apiClient.get(`/api/jobs/${data.jobId}`);
  requests = [];
}

describe('Record answer screen, opened empty (REQ-034)', () => {
  it(
    'says which paid accounts recording needs, above the four workbench parts',
    async () => {
      renderAdmin('/library/record');

      expect(
        await screen.findByRole('heading', { name: 'Record answer', level: 1 }),
      ).toBeVisible();
      expect(
        screen.getByText(
          'Recording needs an active LiveAvatar account and a paid ElevenLabs plan.',
        ),
      ).toBeInTheDocument();
      expect(
        screen.getByRole('heading', { name: 'Text to speech' }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole('heading', { name: 'Avatar session' }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole('heading', { name: 'Recording' }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole('heading', { name: 'Diagnostics' }),
      ).toBeInTheDocument();
      // The workflow order, on every width (ruling 8).
      expect(
        screen
          .getAllByRole('heading', { level: 2 })
          .map((heading) => heading.textContent)
          .slice(0, 4),
      ).toEqual([
        'Text to speech',
        'Avatar session',
        'Recording',
        'Save to library',
      ]);
      // The composer is the admin's own text box here, not read only.
      expect(
        screen.getByRole('textbox', { name: 'Persian text' }),
      ).not.toHaveAttribute('readonly');
      expect(
        within(saveForm()).getByRole('button', { name: 'Save to library' }),
      ).toBeDisabled();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'asks for a 300 second session (REQ-035)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });

      await startSession(user);

      const [sessionRequest] = requestsTo('post', /\/api\/avatar\/session$/);
      expect(JSON.parse(String(sessionRequest?.data))).toEqual({
        max_session_duration: 300,
      });
    },
    UI_TEST_TIMEOUT,
  );

  it.each([
    [270_000, false],
    [270_001, true],
  ])(
    'with generated audio of %i ms, Record is disabled: %s (REQ-036)',
    async (durationMs, isDisabled) => {
      const user = setupUser();
      override = (config) =>
        config.url?.endsWith('/api/tts/generate')
          ? reply(config, {
              id: '11111111-1111-4111-8111-111111111111',
              cache_key: 'a'.repeat(64),
              status: 'AUDIO_GENERATED',
              duration_ms: durationMs,
              sample_rate: 24000,
              format: 'pcm_s16le',
              media_url:
                '/api/assets/audio/11111111-1111-4111-8111-111111111111',
              cache_hit: false,
            })
          : undefined;
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await startSession(user);

      await user.click(screen.getByRole('button', { name: 'Generate audio' }));
      await screen.findByText(/Generated by ElevenLabs/);

      const record = screen.getByRole('button', { name: 'Start recording' });
      const tooLong =
        'This answer is too long for one recording. Keep its audio under 4 minutes 30 seconds.';
      if (isDisabled) {
        expect(record).toBeDisabled();
        expect(screen.getByText(tooLong)).toBeInTheDocument();
      } else {
        expect(record).toBeEnabled();
        expect(screen.queryByText(tooLong)).toBeNull();
      }
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'keeps Record off with a hint until the audio of the text exists (ruling 5)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await startSession(user);

      expect(
        screen.getByRole('button', { name: 'Start recording' }),
      ).toBeDisabled();
      expect(screen.getByText(NEEDS_AUDIO)).toBeInTheDocument();

      await generateAudio(user);

      expect(
        screen.getByRole('button', { name: 'Start recording' }),
      ).toBeEnabled();
      expect(screen.queryByText(NEEDS_AUDIO)).toBeNull();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'turns Record off again when the text changes after the audio, even by one space',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await startSession(user);
      await generateAudio(user);
      expect(
        screen.getByRole('button', { name: 'Start recording' }),
      ).toBeEnabled();

      await user.type(
        screen.getByRole('textbox', { name: 'Persian text' }),
        ' ',
      );

      expect(
        screen.getByRole('button', { name: 'Start recording' }),
      ).toBeDisabled();
      expect(screen.getByText(NEEDS_AUDIO)).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'locks the composer to the recorded text while recording, and unlocks it after (ruling 10)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(user, 'متن ضبط‌شده.');
      await startSession(user);
      await generateAudio(user);
      await user.click(screen.getByRole('button', { name: 'Start recording' }));
      await screen.findByRole('button', { name: 'Stop recording' });

      const composer = screen.getByRole('textbox', { name: 'Persian text' });
      expect(composer).toHaveAttribute('readonly');
      expect(composer).toHaveValue('متن ضبط‌شده.');
      await user.type(composer, ' تغییر');
      expect(composer).toHaveValue('متن ضبط‌شده.');

      await user.click(screen.getByRole('button', { name: 'Send to avatar' }));
      await waitFor(() =>
        expect(requestsTo('post', /\/api\/avatar\/speak$/)).toHaveLength(1),
      );
      const [speak] = requestsTo('post', /\/api\/avatar\/speak$/);
      expect(JSON.parse(String(speak?.data))).toMatchObject({
        text: 'متن ضبط‌شده.',
      });

      await user.click(screen.getByRole('button', { name: 'Stop recording' }));
      await waitForJobDone();

      const unlocked = screen.getByRole('textbox', { name: 'Persian text' });
      expect(unlocked).not.toHaveAttribute('readonly');
      await user.type(unlocked, '!');
      expect(unlocked).toHaveValue('متن ضبط‌شده.!');
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows the payment message and the code when ElevenLabs refuses the speech (SC-025)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(
        user,
        `سلام ${mockRecordingTriggers.speechPayment}`,
      );
      await startSession(user);

      await user.click(screen.getByRole('button', { name: 'Send to avatar' }));

      expect(
        await screen.findByText(
          'ElevenLabs refused the speech because the plan is not paid. Pay the ElevenLabs plan, then try again.',
        ),
      ).toBeInTheDocument();
      expect(screen.getByText('elevenlabs_payment')).toHaveAttribute(
        'dir',
        'ltr',
      );
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'polls the finalize job, then saves the recording as a draft entry and opens it (SC-020, SC-023)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(user, 'متن تازه برای ضبط.');
      await fillSaveForm(user, saveForm());

      await recordAndStop(user);
      const saveButton = within(saveForm()).getByRole('button', {
        name: 'Save to library',
      });
      expect(saveButton).toBeDisabled();
      await waitForJobDone();
      expect(requestsTo('get', /\/api\/jobs\//)).toHaveLength(3);
      await waitFor(() => expect(saveButton).toBeEnabled());
      // The finished recording joins the unsaved list at once, so a reload cannot lose it.
      const unsaved = screen.getByRole('region', {
        name: 'Finished recordings not in the library',
      });
      expect(
        await within(unsaved).findByText('متن تازه برای ضبط.'),
      ).toBeInTheDocument();

      await user.click(saveButton);

      const panel = await screen.findByRole('dialog', {
        name: /^Answer AVATAR_/,
      });
      expect(
        within(panel).getByText('Waiting for video review'),
      ).toBeInTheDocument();
      const [create] = requestsTo('post', /\/api\/admin\/library\/entries$/);
      expect(JSON.parse(String(create?.data))).toMatchObject({
        question: 'پرسش تازه',
        language: 'fa',
        category: '5',
        categoryTitle: 'دسته پنج',
        videoAssetId: expect.any(String),
      });
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'keeps the form and shows the message when the key is taken (409)',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await fillSaveForm(user, saveForm(), 'C4Q02');
      await recordAndStop(user);
      await waitForJobDone();

      await user.click(
        within(saveForm()).getByRole('button', { name: 'Save to library' }),
      );

      expect(
        await within(saveForm()).findByText(
          'This key is already used by another answer.',
        ),
      ).toBeInTheDocument();
      expect(
        within(saveForm()).getByRole('textbox', { name: 'Question' }),
      ).toHaveValue('پرسش تازه');
      expect(
        screen.getByRole('heading', { name: 'Record answer', level: 1 }),
      ).toBeVisible();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows the mapped message and the code when the finalize job fails',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(
        user,
        `سلام ${mockRecordingTriggers.finalizeFails}`,
      );

      await recordAndStop(user);
      await advance(4000);

      expect(
        await screen.findByText(
          'The video file did not appear in time. Record the answer again.',
        ),
      ).toBeInTheDocument();
      expect(screen.getByText('egress_failure')).toHaveAttribute('dir', 'ltr');
      expect(
        within(saveForm()).getByRole('button', { name: 'Save to library' }),
      ).toBeDisabled();
      // The recording is gone, so a new one can start.
      expect(
        screen.getByRole('button', { name: 'Start recording' }),
      ).toBeEnabled();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'stops at 180 s with the slow line, and Check again polls the job again',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(user, `سلام ${mockRecordingTriggers.finalizeSlow}`);

      await recordAndStop(user);
      await screen.findByText('Waiting to process the recording');
      for (let elapsed = 0; elapsed < 182_000; elapsed += 2000)
        await advance(2000);

      expect(
        await screen.findByText(
          'The recording is still being processed. Check again in a minute.',
        ),
      ).toBeInTheDocument();
      const pollsAtSlow = requestsTo('get', /\/api\/jobs\//).length;
      await advance(10_000);
      expect(requestsTo('get', /\/api\/jobs\//)).toHaveLength(pollsAtSlow);

      await user.click(screen.getByRole('button', { name: 'Check again' }));

      await waitFor(() =>
        expect(requestsTo('get', /\/api\/jobs\//).length).toBeGreaterThan(
          pollsAtSlow,
        ),
      );
      expect(screen.getByText('Processing the recording')).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows the whole screen in Persian, right to left',
    async () => {
      await i18n.changeLanguage('fa');
      renderAdmin('/library/record', 'fa');

      expect(
        await screen.findByRole('heading', { name: 'ضبط پاسخ', level: 1 }),
      ).toBeVisible();
      expect(
        screen.getByText(
          'ضبط به حساب فعال LiveAvatar و اشتراک پرداخت‌شده ElevenLabs نیاز دارد.',
        ),
      ).toBeInTheDocument();
      expect(
        await screen.findByRole('region', {
          name: 'ضبط‌های آماده‌ای که در کتابخانه نیستند',
        }),
      ).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );
});

describe('Finished recordings not in the library (REQ-042)', () => {
  it(
    'lists each unsaved recording with its text and duration',
    async () => {
      renderAdmin('/library/record');

      const section = await screen.findByRole('region', {
        name: 'Finished recordings not in the library',
      });
      expect(
        await within(section).findByText(SEED_RECORDING_TEXT),
      ).toBeInTheDocument();
      expect(within(section).getByText('5 s')).toBeInTheDocument();
      expect(
        within(section).getByRole('button', { name: 'Save to library' }),
      ).toBeEnabled();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'renders no section when every recording is in the library',
    async () => {
      override = (config) =>
        config.url?.endsWith('/api/admin/library/recordings')
          ? reply(config, { items: [], total: 0, page: 1, pageSize: 10 })
          : undefined;
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await waitFor(() =>
        expect(
          requestsTo('get', /\/api\/admin\/library\/recordings/),
        ).toHaveLength(1),
      );

      await advance(100);
      expect(
        screen.queryByRole('region', {
          name: 'Finished recordings not in the library',
        }),
      ).toBeNull();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows an error with a retry when the list cannot load',
    async () => {
      const user = setupUser();
      let failures = 1;
      override = (config) => {
        if (
          !config.url?.endsWith('/api/admin/library/recordings') ||
          failures === 0
        ) {
          return undefined;
        }
        failures -= 1;
        return errorReply(config, 500, 'internal_error');
      };
      renderAdmin('/library/record');

      const section = await screen.findByRole('region', {
        name: 'Finished recordings not in the library',
      });
      await user.click(
        await within(section).findByRole('button', { name: 'Retry' }),
      );

      expect(
        await within(section).findByText(SEED_RECORDING_TEXT),
      ).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'saves an unsaved recording from its row with the same form',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      const section = await screen.findByRole('region', {
        name: 'Finished recordings not in the library',
      });
      await within(section).findByText(SEED_RECORDING_TEXT);

      await user.click(
        within(section).getByRole('button', { name: 'Save to library' }),
      );
      const dialog = await screen.findByRole('dialog', {
        name: 'Save to library',
      });
      await fillSaveForm(user, dialog);
      await user.click(
        within(dialog).getByRole('button', { name: 'Save to library' }),
      );

      const panel = await screen.findByRole('dialog', {
        name: 'Answer ANS_MOCK_01',
      });
      expect(
        within(panel).getByText('Waiting for video review'),
      ).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'offers Attach only for a ready entry with the same text, and attaches it',
    async () => {
      const user = setupUser();
      await makeFinishedRecording(READY_TEXT);
      renderAdmin('/library/record');
      const section = await screen.findByRole('region', {
        name: 'Finished recordings not in the library',
      });
      const rows = await within(section).findAllByRole('listitem');
      const matching = rows.find((row) => within(row).queryByText(READY_TEXT));
      const other = rows.find((row) =>
        within(row).queryByText(SEED_RECORDING_TEXT),
      );
      if (!matching || !other)
        throw new Error('both recordings should be listed');

      expect(
        within(other).queryByRole('button', { name: /Attach to this answer/ }),
      ).toBeNull();
      await user.click(
        await within(matching).findByRole('button', {
          name: /Attach to this answer/,
        }),
      );

      const panel = await screen.findByRole('dialog', { name: 'Answer C4Q02' });
      expect(
        within(panel).getByText('Waiting for video review'),
      ).toBeInTheDocument();
      const [attach] = requestsTo('patch', /\/status$/);
      expect(JSON.parse(String(attach?.data))).toMatchObject({
        status: 'draft',
        fromStatus: 'ready',
        videoAssetId: expect.any(String),
      });
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'keeps the row and shows the message when Attach answers 409',
    async () => {
      const user = setupUser();
      await makeFinishedRecording(READY_TEXT);
      override = (config) =>
        config.method === 'patch' && config.url?.endsWith('/status')
          ? errorReply(config, 409, 'library_video_in_use')
          : undefined;
      renderAdmin('/library/record');
      const section = await screen.findByRole('region', {
        name: 'Finished recordings not in the library',
      });
      await within(section).findByText(READY_TEXT);

      await user.click(
        await within(section).findByRole('button', {
          name: /Attach to this answer/,
        }),
      );

      expect(
        await within(section).findByText(
          'This video already belongs to another answer.',
        ),
      ).toBeInTheDocument();
      expect(
        screen.getByRole('heading', { name: 'Record answer', level: 1 }),
      ).toBeVisible();
    },
    UI_TEST_TIMEOUT,
  );
});

describe('Record this answer, from a ready entry (REQ-074)', () => {
  it(
    'the ready entry panel opens the Record answer screen with the entry',
    async () => {
      const user = setupUser();
      renderAdmin('/library');
      await user.click(await screen.findByText('C4Q02'));
      const panel = await screen.findByRole('dialog', { name: 'Answer C4Q02' });

      await user.click(
        within(panel).getByRole('button', { name: 'Record this answer' }),
      );

      expect(
        await screen.findByRole('heading', { name: 'Record answer', level: 1 }),
      ).toBeVisible();
      expect(screen.getByRole('textbox', { name: 'Persian text' })).toHaveValue(
        READY_TEXT,
      );
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'the library header links to an empty Record answer screen',
    async () => {
      const user = setupUser();
      renderAdmin('/library');

      await user.click(
        await screen.findByRole('link', { name: 'Record answer' }),
      );

      expect(
        await screen.findByRole('heading', { name: 'Record answer', level: 1 }),
      ).toBeVisible();
      expect(
        screen.getByRole('form', { name: 'Save to library' }),
      ).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'records the approved text read only, then attaches the video to the entry',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record?entry=mock-library-ready&key=C4Q02');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      const composer = await screen.findByRole('textbox', {
        name: 'Persian text',
      });
      await waitFor(() => expect(composer).toHaveValue(READY_TEXT));
      expect(composer).toHaveAttribute('readonly');
      expect(
        screen.queryByRole('form', { name: 'Save to library' }),
      ).toBeNull();
      const attach = screen.getByRole('button', {
        name: 'Attach to this answer',
      });
      expect(attach).toBeDisabled();

      await recordAndStop(user);
      const [generate] = requestsTo('post', /\/api\/assets\/generate-video$/);
      expect(JSON.parse(String(generate?.data))).toMatchObject({
        text: READY_TEXT,
      });
      await waitForJobDone();
      await waitFor(() => expect(attach).toBeEnabled());

      await user.click(attach);

      const panel = await screen.findByRole('dialog', { name: 'Answer C4Q02' });
      expect(
        within(panel).getByText('Waiting for video review'),
      ).toBeInTheDocument();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    "does not offer another answer's finished recording for this entry (ruling 7)",
    async () => {
      const user = setupUser();
      renderAdmin('/library/record');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await setComposerText(user, 'متن پاسخ دیگری.');
      await recordAndStop(user);
      await waitForJobDone();

      // Out to the library and back in through the ready entry C4Q02, in the same tab.
      await user.click(screen.getByRole('link', { name: 'Answer library' }));
      await user.click(await screen.findByText('C4Q02'));
      const panel = await screen.findByRole('dialog', { name: 'Answer C4Q02' });
      await user.click(
        within(panel).getByRole('button', { name: 'Record this answer' }),
      );
      await waitFor(() =>
        expect(
          screen.getByRole('textbox', { name: 'Persian text' }),
        ).toHaveValue(READY_TEXT),
      );

      expect(entryAttachButton()).toBeDisabled();
      expect(
        screen.queryByText('The recording is ready. Save it to the library.'),
      ).toBeNull();
      // Ruling 11: the disabled Attach says why.
      const hint =
        'This recording is of another answer. You can find it in the list below.';
      expect(screen.getByText(hint)).toBeInTheDocument();
      expect(entryAttachButton()).toHaveAccessibleDescription(hint);
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows the mismatch message when the attach answers 409 library_text_mismatch',
    async () => {
      const user = setupUser();
      renderAdmin('/library/record?entry=mock-library-ready&key=C4Q02');
      await screen.findByRole('heading', { name: 'Record answer', level: 1 });
      await waitFor(() =>
        expect(
          screen.getByRole('textbox', { name: 'Persian text' }),
        ).toHaveValue(READY_TEXT),
      );
      await recordAndStop(user);
      await waitForJobDone();
      override = (config) =>
        config.method === 'patch' && config.url?.endsWith('/status')
          ? errorReply(config, 409, 'library_text_mismatch')
          : undefined;

      await user.click(entryAttachButton());

      expect(
        await screen.findByText(
          'This video does not say the approved text of this answer.',
        ),
      ).toBeInTheDocument();
      expect(entryAttachButton()).toBeEnabled();
    },
    UI_TEST_TIMEOUT,
  );

  it(
    'shows an error with a retry when the entry cannot be found',
    async () => {
      renderAdmin('/library/record?entry=missing&key=NOPE');

      expect(
        await screen.findByRole('button', { name: 'Retry' }),
      ).toBeInTheDocument();
      expect(
        screen.queryByRole('button', { name: 'Start recording' }),
      ).toBeNull();
    },
    UI_TEST_TIMEOUT,
  );
});
