import { expect, test, type Page } from '@playwright/test';
import { installFakeLiveKitClient } from './utils/fakeLiveKitClient';

/*
 * The Record answer screen in the admin target (REQ-034 to REQ-036, REQ-039, REQ-041, REQ-042,
 * REQ-074), against the in-browser mock API. The mock runs the recording chain: its finalize job
 * answers queued, running, then done, one step per 2 second poll, and a marker in the text picks
 * a failure (`mockRecordingTriggers` in src/data/mock/handlers.ts). LiveKit is the fake of
 * `utils/fakeLiveKitClient.ts`. Every page load starts from the mock seed: C4Q02 is `ready`.
 */

const ADMIN_PHONE = '09121234567';
const READY_TEXT = 'پاسخ گفتاری نمونه.';

async function login(page: Page) {
  await installFakeLiveKitClient(page);
  await page.goto('/login');
  await page.getByLabel('Phone number').fill(ADMIN_PHONE);
  await page.getByRole('button', { name: 'Send code' }).click();
  await page.getByLabel('One-time code').fill('123456');
  await expect(
    page.getByRole('link', { name: 'Answer library' }),
  ).toBeVisible();
}

async function openRecordAnswer(page: Page) {
  await login(page);
  await page.getByRole('link', { name: 'Answer library' }).click();
  await page.getByRole('link', { name: 'Record answer' }).click();
  await expect(
    page.getByRole('heading', { name: 'Record answer', level: 1 }),
  ).toBeVisible();
}

async function setText(page: Page, text: string) {
  await page.getByRole('textbox', { name: 'Persian text' }).fill(text);
}

async function startSession(page: Page) {
  await page.getByRole('button', { name: 'Start avatar' }).click();
  await expect(
    page.getByRole('button', { name: 'Close session' }),
  ).toBeEnabled();
}

/**
 * The mock job ends at its third poll. Polls are 2 s apart plus the mock's 400 ms delay, so the
 * end shows about 5.5 s after Stop, past the default 5 s of an assertion.
 */
const JOB_END = { timeout: 15_000 };

/** Record needs the audio of the text on screen first, so its length is known (ruling 5). */
async function generateAudio(page: Page) {
  await page.getByRole('button', { name: 'Generate audio' }).click();
  await expect(page.getByText('Generated by ElevenLabs')).toBeVisible();
}

async function recordAndStop(page: Page) {
  await startSession(page);
  await generateAudio(page);
  await page.getByRole('button', { name: 'Start recording' }).click();
  await page.getByRole('button', { name: 'Stop recording' }).click();
}

test('an empty screen says what recording needs, then saves a recording as a draft (REQ-034, REQ-039, REQ-041)', async ({
  page,
}) => {
  await openRecordAnswer(page);
  await expect(
    page.getByText(
      'Recording needs an active LiveAvatar account and a paid ElevenLabs plan.',
    ),
  ).toBeVisible();

  await setText(page, 'متن تازه برای ضبط.');
  const form = page.getByRole('form', { name: 'Save to library' });
  await form.getByRole('textbox', { name: 'Question' }).fill('پرسش تازه');
  await form.getByRole('textbox', { name: 'Category number' }).fill('5');
  await form.getByRole('textbox', { name: 'Category title' }).fill('دسته پنج');
  await expect(
    form.getByRole('button', { name: 'Save to library' }),
  ).toBeDisabled();

  await recordAndStop(page);
  await expect(
    page.getByText('Waiting to process the recording'),
  ).toBeVisible();
  await expect(page.getByText('Processing the recording')).toBeVisible();
  await expect(
    page.getByText('The recording is ready. Save it to the library.'),
  ).toBeVisible(JOB_END);
  await form.getByRole('button', { name: 'Save to library' }).click();

  await expect(page).toHaveURL(/\/library$/);
  const panel = page.getByRole('dialog', { name: /^Answer AVATAR_/ });
  await expect(panel.getByText('Waiting for video review')).toBeVisible();
});

test('audio over 270 000 ms keeps Record off with the too-long message (REQ-036)', async ({
  page,
}) => {
  await openRecordAnswer(page);
  // The mock speaks 70 ms per character, so 4000 characters are 280 seconds of audio.
  await setText(page, 'ب'.repeat(4000));
  await startSession(page);

  await page.getByRole('button', { name: 'Generate audio' }).click();

  await expect(
    page.getByText(
      'This answer is too long for one recording. Keep its audio under 4 minutes 30 seconds.',
    ),
  ).toBeVisible();
  await expect(
    page.getByRole('button', { name: 'Start recording' }),
  ).toBeDisabled();
});

test('Record waits for the audio of the text, and a changed text needs new audio (ruling 5)', async ({
  page,
}) => {
  await openRecordAnswer(page);
  await setText(page, 'متن تازه برای ضبط.');
  await startSession(page);
  const record = page.getByRole('button', { name: 'Start recording' });
  const hint = page.getByText(
    'Generate the audio first, so its length can be checked.',
  );
  await expect(record).toBeDisabled();
  await expect(hint).toBeVisible();

  await generateAudio(page);
  await expect(record).toBeEnabled();
  await expect(hint).toHaveCount(0);

  await page.getByRole('textbox', { name: 'Persian text' }).press('End');
  await page
    .getByRole('textbox', { name: 'Persian text' })
    .pressSequentially(' ');
  await expect(record).toBeDisabled();
  await expect(hint).toBeVisible();
});

test('an unpaid ElevenLabs plan shows its own message with the code (SC-025)', async ({
  page,
}) => {
  await openRecordAnswer(page);
  await setText(page, 'سلام #payment');
  await startSession(page);

  await page.getByRole('button', { name: 'Send to avatar' }).click();

  await expect(
    page.getByText(
      'ElevenLabs refused the speech because the plan is not paid. Pay the ElevenLabs plan, then try again.',
    ),
  ).toBeVisible();
  await expect(
    page.getByText('elevenlabs_payment', { exact: true }),
  ).toBeVisible();
});

test('a failed finalize job asks for a new recording, with the code', async ({
  page,
}) => {
  await openRecordAnswer(page);
  await setText(page, 'سلام #fail');

  await recordAndStop(page);

  await expect(
    page.getByText(
      'The video file did not appear in time. Record the answer again.',
    ),
  ).toBeVisible(JOB_END);
  await expect(page.getByText('egress_failure', { exact: true })).toBeVisible();
  await expect(
    page.getByRole('button', { name: 'Start recording' }),
  ).toBeEnabled();
});

test('after 180 s the job is slow, and Check again polls it again (REQ-041)', async ({
  page,
}) => {
  await page.clock.install();
  await openRecordAnswer(page);
  await setText(page, 'سلام #slow');
  await recordAndStop(page);
  await expect(page.getByText('Processing the recording')).toBeVisible();

  await page.clock.fastForward('03:05');

  await expect(
    page.getByText(
      'The recording is still being processed. Check again in a minute.',
    ),
  ).toBeVisible();
  await page.getByRole('button', { name: 'Check again' }).click();
  await expect(page.getByText('Processing the recording')).toBeVisible();
});

test('Record this answer on a ready entry records its text and attaches the video (REQ-074)', async ({
  page,
}) => {
  await login(page);
  await page.getByRole('link', { name: 'Answer library' }).click();
  await page.getByRole('grid').getByText('C4Q02', { exact: true }).click();
  await page
    .getByRole('dialog', { name: 'Answer C4Q02' })
    .getByRole('button', { name: 'Record this answer' })
    .click();

  const composer = page.getByRole('textbox', { name: 'Persian text' });
  await expect(composer).toHaveValue(READY_TEXT);
  await expect(composer).toHaveAttribute('readonly', '');
  // The screen's own button comes first. Once the recording is done, the unsaved list below
  // offers an Attach for the same entry too.
  const attach = page
    .getByRole('button', { name: 'Attach to this answer' })
    .first();
  await expect(attach).toBeDisabled();

  await recordAndStop(page);
  await expect(
    page.getByText('The recording is ready. Save it to the library.'),
  ).toBeVisible(JOB_END);
  await attach.click();

  const panel = page.getByRole('dialog', { name: 'Answer C4Q02' });
  await expect(panel.getByText('Waiting for video review')).toBeVisible();
});

test('a recording left behind by a reload is listed, and attaches to its ready entry (REQ-042)', async ({
  page,
}) => {
  await login(page);
  await page.goto('/library/record?entry=mock-library-ready&key=C4Q02');
  await expect(page.getByRole('textbox', { name: 'Persian text' })).toHaveValue(
    READY_TEXT,
  );
  await recordAndStop(page);
  await expect(
    page.getByText('The recording is ready. Save it to the library.'),
  ).toBeVisible(JOB_END);

  // A client-side move, so the in-page mock keeps its recording: a real reload would reset it.
  await page.getByRole('link', { name: 'Answer library' }).first().click();
  await page.getByRole('link', { name: 'Record answer' }).click();

  const unsaved = page.getByRole('region', {
    name: 'Finished recordings not in the library',
  });
  const row = unsaved.getByRole('listitem').filter({ hasText: READY_TEXT });
  await row.getByRole('button', { name: 'Attach to this answer' }).click();

  const panel = page.getByRole('dialog', { name: 'Answer C4Q02' });
  await expect(panel.getByText('Waiting for video review')).toBeVisible();
});

test('the screen renders right to left in Persian at phone width', async ({
  page,
}) => {
  await openRecordAnswer(page);
  // Phone width only after login: the sidebar link sits behind the menu button there.
  await page.setViewportSize({ width: 390, height: 844 });

  await page.evaluate(() => {
    const saved = JSON.parse(
      window.localStorage.getItem('settings') ?? '{}',
    ) as object;
    window.localStorage.setItem(
      'settings',
      JSON.stringify({ ...saved, language: 'fa' }),
    );
  });
  await page.reload();

  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl');
  await expect(
    page.getByRole('heading', { name: 'ضبط پاسخ', level: 1 }),
  ).toBeVisible();
  const overflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth -
      document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(0);
});
